ci: test check annotations

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,11 @@ jobs:
         with:
           toolchain: ${{ matrix.toolchain }}
       - name: Check
-        run: cargo check --all-targets
+        run: |
+          cargo check --all-targets || {
+            echo "::error::Cargo check failed"
+            exit 1
+          }
       - name: Test
         run: cargo test --all-targets
 
